/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as BeforeAuthImport } from './routes/_before-auth'
import { Route as R403Import } from './routes/403'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardSuperAdminImport } from './routes/_dashboard/_super-admin'
import { Route as DashboardMasterUserImport } from './routes/_dashboard/_master-user'
import { Route as BeforeAuthVerifyOtpImport } from './routes/_before-auth/verify-otp'
import { Route as BeforeAuthLoginImport } from './routes/_before-auth/login'
import { Route as BeforeAuthForgotPasswordImport } from './routes/_before-auth/forgot-password'
import { Route as BeforeAuthChangePasswordImport } from './routes/_before-auth/change-password'
import { Route as DashboardSuperAdminServiceNumberManagementImport } from './routes/_dashboard/_super-admin/service-number-management'
import { Route as DashboardMasterUserSelectServiceImport } from './routes/_dashboard/_master-user/select-service'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BeforeAuthRoute = BeforeAuthImport.update({
  id: '/_before-auth',
  getParentRoute: () => rootRoute,
} as any)

const R403Route = R403Import.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardSuperAdminRoute = DashboardSuperAdminImport.update({
  id: '/_super-admin',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMasterUserRoute = DashboardMasterUserImport.update({
  id: '/_master-user',
  getParentRoute: () => DashboardRoute,
} as any)

const BeforeAuthVerifyOtpRoute = BeforeAuthVerifyOtpImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => BeforeAuthRoute,
} as any)

const BeforeAuthLoginRoute = BeforeAuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BeforeAuthRoute,
} as any)

const BeforeAuthForgotPasswordRoute = BeforeAuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => BeforeAuthRoute,
} as any)

const BeforeAuthChangePasswordRoute = BeforeAuthChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => BeforeAuthRoute,
} as any)

const DashboardSuperAdminServiceNumberManagementRoute =
  DashboardSuperAdminServiceNumberManagementImport.update({
    id: '/service-number-management',
    path: '/service-number-management',
    getParentRoute: () => DashboardSuperAdminRoute,
  } as any)

const DashboardMasterUserSelectServiceRoute =
  DashboardMasterUserSelectServiceImport.update({
    id: '/select-service',
    path: '/select-service',
    getParentRoute: () => DashboardMasterUserRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403Import
      parentRoute: typeof rootRoute
    }
    '/_before-auth': {
      id: '/_before-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BeforeAuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_before-auth/change-password': {
      id: '/_before-auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof BeforeAuthChangePasswordImport
      parentRoute: typeof BeforeAuthImport
    }
    '/_before-auth/forgot-password': {
      id: '/_before-auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof BeforeAuthForgotPasswordImport
      parentRoute: typeof BeforeAuthImport
    }
    '/_before-auth/login': {
      id: '/_before-auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BeforeAuthLoginImport
      parentRoute: typeof BeforeAuthImport
    }
    '/_before-auth/verify-otp': {
      id: '/_before-auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof BeforeAuthVerifyOtpImport
      parentRoute: typeof BeforeAuthImport
    }
    '/_dashboard/_master-user': {
      id: '/_dashboard/_master-user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardMasterUserImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/_super-admin': {
      id: '/_dashboard/_super-admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardSuperAdminImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/_master-user/select-service': {
      id: '/_dashboard/_master-user/select-service'
      path: '/select-service'
      fullPath: '/select-service'
      preLoaderRoute: typeof DashboardMasterUserSelectServiceImport
      parentRoute: typeof DashboardMasterUserImport
    }
    '/_dashboard/_super-admin/service-number-management': {
      id: '/_dashboard/_super-admin/service-number-management'
      path: '/service-number-management'
      fullPath: '/service-number-management'
      preLoaderRoute: typeof DashboardSuperAdminServiceNumberManagementImport
      parentRoute: typeof DashboardSuperAdminImport
    }
  }
}

// Create and export the route tree

interface BeforeAuthRouteChildren {
  BeforeAuthChangePasswordRoute: typeof BeforeAuthChangePasswordRoute
  BeforeAuthForgotPasswordRoute: typeof BeforeAuthForgotPasswordRoute
  BeforeAuthLoginRoute: typeof BeforeAuthLoginRoute
  BeforeAuthVerifyOtpRoute: typeof BeforeAuthVerifyOtpRoute
}

const BeforeAuthRouteChildren: BeforeAuthRouteChildren = {
  BeforeAuthChangePasswordRoute: BeforeAuthChangePasswordRoute,
  BeforeAuthForgotPasswordRoute: BeforeAuthForgotPasswordRoute,
  BeforeAuthLoginRoute: BeforeAuthLoginRoute,
  BeforeAuthVerifyOtpRoute: BeforeAuthVerifyOtpRoute,
}

const BeforeAuthRouteWithChildren = BeforeAuthRoute._addFileChildren(
  BeforeAuthRouteChildren,
)

interface DashboardMasterUserRouteChildren {
  DashboardMasterUserSelectServiceRoute: typeof DashboardMasterUserSelectServiceRoute
}

const DashboardMasterUserRouteChildren: DashboardMasterUserRouteChildren = {
  DashboardMasterUserSelectServiceRoute: DashboardMasterUserSelectServiceRoute,
}

const DashboardMasterUserRouteWithChildren =
  DashboardMasterUserRoute._addFileChildren(DashboardMasterUserRouteChildren)

interface DashboardSuperAdminRouteChildren {
  DashboardSuperAdminServiceNumberManagementRoute: typeof DashboardSuperAdminServiceNumberManagementRoute
}

const DashboardSuperAdminRouteChildren: DashboardSuperAdminRouteChildren = {
  DashboardSuperAdminServiceNumberManagementRoute:
    DashboardSuperAdminServiceNumberManagementRoute,
}

const DashboardSuperAdminRouteWithChildren =
  DashboardSuperAdminRoute._addFileChildren(DashboardSuperAdminRouteChildren)

interface DashboardRouteChildren {
  DashboardMasterUserRoute: typeof DashboardMasterUserRouteWithChildren
  DashboardSuperAdminRoute: typeof DashboardSuperAdminRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMasterUserRoute: DashboardMasterUserRouteWithChildren,
  DashboardSuperAdminRoute: DashboardSuperAdminRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '': typeof DashboardSuperAdminRouteWithChildren
  '/change-password': typeof BeforeAuthChangePasswordRoute
  '/forgot-password': typeof BeforeAuthForgotPasswordRoute
  '/login': typeof BeforeAuthLoginRoute
  '/verify-otp': typeof BeforeAuthVerifyOtpRoute
  '/select-service': typeof DashboardMasterUserSelectServiceRoute
  '/service-number-management': typeof DashboardSuperAdminServiceNumberManagementRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '': typeof DashboardSuperAdminRouteWithChildren
  '/change-password': typeof BeforeAuthChangePasswordRoute
  '/forgot-password': typeof BeforeAuthForgotPasswordRoute
  '/login': typeof BeforeAuthLoginRoute
  '/verify-otp': typeof BeforeAuthVerifyOtpRoute
  '/select-service': typeof DashboardMasterUserSelectServiceRoute
  '/service-number-management': typeof DashboardSuperAdminServiceNumberManagementRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_before-auth': typeof BeforeAuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_before-auth/change-password': typeof BeforeAuthChangePasswordRoute
  '/_before-auth/forgot-password': typeof BeforeAuthForgotPasswordRoute
  '/_before-auth/login': typeof BeforeAuthLoginRoute
  '/_before-auth/verify-otp': typeof BeforeAuthVerifyOtpRoute
  '/_dashboard/_master-user': typeof DashboardMasterUserRouteWithChildren
  '/_dashboard/_super-admin': typeof DashboardSuperAdminRouteWithChildren
  '/_dashboard/_master-user/select-service': typeof DashboardMasterUserSelectServiceRoute
  '/_dashboard/_super-admin/service-number-management': typeof DashboardSuperAdminServiceNumberManagementRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | ''
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/verify-otp'
    | '/select-service'
    | '/service-number-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | ''
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/verify-otp'
    | '/select-service'
    | '/service-number-management'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_before-auth'
    | '/_dashboard'
    | '/_before-auth/change-password'
    | '/_before-auth/forgot-password'
    | '/_before-auth/login'
    | '/_before-auth/verify-otp'
    | '/_dashboard/_master-user'
    | '/_dashboard/_super-admin'
    | '/_dashboard/_master-user/select-service'
    | '/_dashboard/_super-admin/service-number-management'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  BeforeAuthRoute: typeof BeforeAuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  BeforeAuthRoute: BeforeAuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/403",
        "/_before-auth",
        "/_dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/403": {
      "filePath": "403.tsx"
    },
    "/_before-auth": {
      "filePath": "_before-auth.tsx",
      "children": [
        "/_before-auth/change-password",
        "/_before-auth/forgot-password",
        "/_before-auth/login",
        "/_before-auth/verify-otp"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/_master-user",
        "/_dashboard/_super-admin"
      ]
    },
    "/_before-auth/change-password": {
      "filePath": "_before-auth/change-password.tsx",
      "parent": "/_before-auth"
    },
    "/_before-auth/forgot-password": {
      "filePath": "_before-auth/forgot-password.tsx",
      "parent": "/_before-auth"
    },
    "/_before-auth/login": {
      "filePath": "_before-auth/login.tsx",
      "parent": "/_before-auth"
    },
    "/_before-auth/verify-otp": {
      "filePath": "_before-auth/verify-otp.tsx",
      "parent": "/_before-auth"
    },
    "/_dashboard/_master-user": {
      "filePath": "_dashboard/_master-user.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/_master-user/select-service"
      ]
    },
    "/_dashboard/_super-admin": {
      "filePath": "_dashboard/_super-admin.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/_super-admin/service-number-management"
      ]
    },
    "/_dashboard/_master-user/select-service": {
      "filePath": "_dashboard/_master-user/select-service.tsx",
      "parent": "/_dashboard/_master-user"
    },
    "/_dashboard/_super-admin/service-number-management": {
      "filePath": "_dashboard/_super-admin/service-number-management.tsx",
      "parent": "/_dashboard/_super-admin"
    }
  }
}
ROUTE_MANIFEST_END */
